#!/bin/bash
set -euo pipefail

# refresh-channels.sh — Download the built-in Roku playlist.
# The list is regenerated upstream (BuddyChewChew/app-m3u-generator) around
# daily; jmp2.uk redirects re-mint fresh stream URLs, so refreshing re-arms
# tokens that have rotted.
#
# Why only Roku? Other candidates are blocked or dead upstream:
#   - Samsung TV Plus (US): master.m3u8 -> HTTP 403 (Akamai attestation).
#     samsungtvplus_ca serves masters but every segment 403s.
#   - Pluto TV: shared JWT (sub="samsungtvplus") expires ~1/day upstream and
#     cannot be re-minted client-side -> HTTP 400 everywhere.
#   - Plex FAST (plex_us): plays on a shared Plex token but only ~10% of the
#     693 channels actually return video; left on disk as an opt-in.
#
# Usage: refresh-channels.sh
# Writes: <plugin>/channels/roku.m3u + .refreshed (unix ts)

PLUGIN_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CHANNELS_DIR="$PLUGIN_DIR/channels"
mkdir -p "$CHANNELS_DIR"

# Stale variant-unfolded playlists are regenerated by the controller.
rm -rf "$CHANNELS_DIR/.flat"

BASE="https://raw.githubusercontent.com/BuddyChewChew/app-m3u-generator/main/playlists"

ok=0
if curl -fsSL --connect-timeout 15 --max-time 90 "$BASE/roku_all.m3u" \
    -o "$CHANNELS_DIR/roku.m3u" 2>/dev/null; then
  echo "ok  roku.m3u"
  ok=1
else
  echo "ERR roku.m3u"
fi

date +%s > "$CHANNELS_DIR/.refreshed" 2>/dev/null || true

if [ "$ok" = "1" ]; then
  exit 0
else
  exit 1
fi